import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../data/app_state.dart';
import '../data/catalog_data.dart';
import '../theme/app_theme.dart';
import '../utils/formatters.dart';
import '../utils/friendly_error.dart';
import 'chat_screen.dart';

class WantedScreen extends StatefulWidget{const WantedScreen({super.key});@override State<WantedScreen> createState()=>_WantedScreenState();}
class _WantedScreenState extends State<WantedScreen>{
  List<Map<String,dynamic>> _items=[];String? _city;bool _loading=true;
  Future<void> _load()async{try{var q=Supabase.instance.client.from('wanted_requests').select('*').eq('status','open');if(_city!=null)q=q.eq('city',_city!);final rows=await q.order('created_at',ascending:false);if(mounted)setState(()=>_items=List<Map<String,dynamic>>.from(rows));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyError(e,fallback:'تعذر تحميل الطلبات.'))));}finally{if(mounted)setState(()=>_loading=false);}}
  @override void initState(){super.initState();_load();}
  Future<void> _add()async{final s=context.read<AppState>();if(!s.isLoggedIn){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('سجّل الدخول أولاً')));return;}final model=TextEditingController(),price=TextEditingController(),notes=TextEditingController();String? city;await showDialog(context:context,builder:(d)=>AlertDialog(title:const Text('اطلب هاتفاً'),content:SingleChildScrollView(child:Column(children:[TextField(controller:model,maxLength:80,decoration:const InputDecoration(labelText:'الموديل المطلوب')),TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'أقصى سعر (ج.س)')),DropdownButtonFormField<String>(decoration:const InputDecoration(labelText:'المدينة'),items:CatalogData.cities.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>city=v),TextField(controller:notes,maxLength:300,maxLines:3,decoration:const InputDecoration(labelText:'ملاحظات اختيارية'))])),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('إلغاء')),ElevatedButton(onPressed:()async{final p=int.tryParse(price.text.trim());if(model.text.trim().isEmpty||p==null||p<=0||city==null)return;await Supabase.instance.client.from('wanted_requests').insert({'user_id':s.currentUser!.id,'model_text':model.text.trim(),'max_price':p,'city':city,'notes':notes.text.trim().isEmpty?null:notes.text.trim()});if(context.mounted){Navigator.pop(d);_load();}},child:const Text('نشر'))]));model.dispose();price.dispose();notes.dispose();}
  Future<void> _respond(Map<String,dynamic> item)async{final s=context.read<AppState>();if(!s.isLoggedIn){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('سجّل الدخول أولاً')));return;}final rows=await Supabase.instance.client.from('listings').select('id,title,brand,price,city').eq('seller_id',s.currentUser!.id).eq('status','active').order('created_at',ascending:false);if(!mounted)return;if((rows as List).isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('انشر إعلانك أولاً')));return;}final selected=await showDialog<Map<String,dynamic>>(context:context,builder:(d)=>AlertDialog(title:const Text('اختر إعلانك'),content:SizedBox(width:360,child:ListView(shrinkWrap:true,children:rows.map((x)=>ListTile(title:Text(x['title']),subtitle:Text(x['price'].toString()+' ج.س • '+x['city'].toString()),onTap:()=>Navigator.pop(d,Map<String,dynamic>.from(x)))).toList()))));if(selected==null)return;try{final tid=await Supabase.instance.client.rpc('start_wanted_chat',params:{'p_request_id':item['id'],'p_listing_id':selected['id']});final listing=await s.getListingById(selected['id']);if(mounted&&listing!=null)Navigator.push(context,MaterialPageRoute(builder:(_)=>ChatScreen(listing:listing)));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyError(e,fallback:'تعذر بدء المحادثة.'))));}}
  Future<void> _close(Map<String,dynamic> item,{bool delete=false})async{try{if(delete){await Supabase.instance.client.from('wanted_requests').delete().eq('id',item['id']);}else{await Supabase.instance.client.from('wanted_requests').update({'status':'closed'}).eq('id',item['id']);}_load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyError(e,fallback:'تعذر تنفيذ العملية.'))));}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('مطلوب'),actions:[IconButton(onPressed:_add,icon:const Icon(Icons.add))]),body:Column(children:[Padding(padding:const EdgeInsets.all(10),child:DropdownButtonFormField<String>(value:_city,decoration:const InputDecoration(labelText:'فلتر المدينة'),items:[const DropdownMenuItem<String>(value:null,child:Text('كل المدن')), ...CatalogData.cities.map((x)=>DropdownMenuItem(value:x,child:Text(x)))],onChanged:(v){setState(()=>_city=v);_loading=true;_load();}}),Expanded(child:_loading?const Center(child:CircularProgressIndicator(color:AppColors.gold)):_items.isEmpty?const Center(child:Text('لا توجد طلبات مفتوحة')):ListView.builder(itemCount:_items.length,itemBuilder:(_,i){final x=_items[i];final mine=x['user_id']==context.read<AppState>().currentUser?.id;return Card(margin:const EdgeInsets.symmetric(horizontal:12,vertical:5),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x['model_text'],style:const TextStyle(fontWeight:FontWeight.bold)),Text(x['max_price'].toString()+' ج.س • '+x['city'].toString()+' • '+AppFormatters.timeAgo(DateTime.parse(x['created_at'].toString()))),if((x['notes']??'').toString().isNotEmpty)Text(x['notes']),const SizedBox(height:7),Row(children:[if(!mine)Expanded(child:OutlinedButton(onPressed:()=>_respond(x),child:const Text('عندي هذا الهاتف'))),if(mine)...[Expanded(child:OutlinedButton(onPressed:()=>_close(x),child:const Text('تم الشراء'))),const SizedBox(width:6),IconButton(onPressed:()=>_close(x,delete:true),icon:const Icon(Icons.delete_outline))]])])));}]))]));
}
